version: '3.8'

# Conteneurs crées
services:

  # Conteneur spring boot
  springboot-app:
    build: . # Construit l'image à partir du Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/trikountBDD
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    depends_on:
      - db # Force démarrage BDD avant spring boot
    networks:
      - app-network # connecter réseau interne


  # Conteneur PostgreSQL
  db: 
    image: postgres:latest # Utilise l'image officielle de PostgreSQL.
    environment: # Configure la base de données créée au démarrage
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trikountBDD
    ports:
      - "5433:5432"
    volumes: # volume nommé pgdata pour garder les données PostgreSQL persistantes
      - pgdata:/var/lib/postgresql/data
    networks: # Connecté au réseau
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
